/**
 * Official-style transcript PDF: one table per term, with term GPA, cumulative
 * GPA, credits earned and academic standing.
 */
import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

import { downloadBlob } from '../utils/downloadFile'
import { readInstitutionName } from '../storage/readers'
import type { Transcript } from './transcript'

const NAVY: [number, number, number] = [27, 35, 64]

export function transcriptFileName(transcript: Transcript): string {
  const safe = transcript.studentName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
  return `transcript-${safe || transcript.studentId}-${new Date().toISOString().slice(0, 10)}.pdf`
}

export function exportTranscriptPdf(transcript: Transcript): void {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const institution = readInstitutionName()
  const margin = 40
  let y = 50

  doc.setTextColor(...NAVY)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.text(institution, margin, y)
  y += 20
  doc.setFontSize(12)
  doc.text('Academic Transcript', margin, y)

  y += 24
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.text(`Student: ${transcript.studentName}`, margin, y)
  doc.text(`Student ID: ${transcript.studentId}`, margin + 280, y)
  y += 14
  doc.text(`Program: ${transcript.program}`, margin, y)
  doc.text(`Issued: ${new Date().toLocaleDateString()}`, margin + 280, y)

  for (const term of transcript.terms) {
    autoTable(doc, {
      startY: y + 18,
      head: [[term.termName, 'Credits', 'Score', 'Grade', 'Points']],
      body: term.courses.map((course) => [
        `${course.code} — ${course.title}`,
        course.credits ? String(course.credits) : '—',
        course.percent === null ? 'In progress' : `${course.percent}%`,
        course.letter ?? '—',
        course.points === null ? '—' : course.points.toFixed(2),
      ]),
      foot: [
        [
          `Term GPA: ${term.gpa === null ? '—' : term.gpa.toFixed(2)}`,
          `${term.creditsEarned}/${term.creditsAttempted}`,
          '',
          '',
          '',
        ],
      ],
      theme: 'grid',
      headStyles: { fillColor: NAVY, textColor: 255, fontSize: 9 },
      footStyles: { fillColor: [243, 245, 249], textColor: NAVY, fontStyle: 'bold', fontSize: 9 },
      bodyStyles: { fontSize: 9 },
      margin: { left: margin, right: margin },
    })
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY
  }

  autoTable(doc, {
    startY: y + 22,
    body: [
      ['Cumulative GPA', transcript.cumulativeGpa === null ? '—' : transcript.cumulativeGpa.toFixed(2)],
      ['Credits earned', `${transcript.creditsEarned} of ${transcript.creditsAttempted} attempted`],
      ['Academic standing', transcript.standing ?? '—'],
    ],
    theme: 'plain',
    bodyStyles: { fontSize: 10, textColor: NAVY, fontStyle: 'bold' },
    margin: { left: margin, right: margin },
  })

  const finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(120)
  doc.text(
    'Unofficial transcript generated by Berana LMS. Grades shown reflect work graded to date.',
    margin,
    finalY + 26,
  )

  downloadBlob(transcriptFileName(transcript), doc.output('blob'))
}
