import type { EditionConfig } from './types'

const corporateTerminology = {
  organization: 'Organization',
  location: 'Branch / Office',
  department: 'Department',
  team: 'Team',
  employee: 'Employee',
  employees: 'Employees',
  trainer: 'Trainer',
  training: 'Training',
  trainingCatalog: 'Training Catalog',
  trainingAssignment: 'Training Assignments',
  course: 'Training module',
  enrollment: 'Assignment',
  certificate: 'Certification',
  compliance: 'Compliance',
  adminRole: 'Learning Admin',
  learnerPortal: 'Employee Portal',
  cohort: 'Cohort',
  cohorts: 'Cohorts',
  trainingProgram: 'Training Program',
  trainingPrograms: 'Training Programs',
  trainingDivision: 'Division',
  trainingDivisions: 'Divisions',
  learner: 'Employee',
  learners: 'Employees',
} as const

export const corporateEditionConfig: EditionConfig = {
  edition: 'corporate',
  tenantType: 'business',
  defaultOrganizationName: 'Horizon Bank',
  terminology: corporateTerminology,
  modules: {
    campuses: false,
    colleges: false,
    programs: false,
    students: false,
    instructors: true,
    guardians: false,
    enrollments: true,
    teams: true,
    employees: true,
    compliance: true,
  },
  navSections: [
    {
      title: 'Main',
      items: [
        {
          id: 'dashboard',
          label: 'Dashboard',
          to: '/admin',
          iconKey: 'dashboard',
          activePaths: ['/admin'],
        },
        {
          id: 'organization',
          label: 'Organization Structure',
          to: '/admin/organization',
          iconKey: 'organization',
          activePaths: ['/admin/organization'],
        },
      ],
    },
    {
      title: 'Workforce',
      items: [
        {
          id: 'employees',
          label: 'Employees',
          to: '/admin/employees',
          iconKey: 'employees',
          activePaths: ['/admin/employees'],
          moduleKey: 'employees',
        },
        {
          id: 'departments',
          label: 'Departments',
          to: '/admin/departments',
          iconKey: 'departments',
          activePaths: ['/admin/departments'],
        },
        {
          id: 'teams',
          label: 'Teams',
          to: '/admin/teams',
          iconKey: 'teams',
          activePaths: ['/admin/teams'],
          moduleKey: 'teams',
        },
        {
          id: 'job-roles',
          label: 'Job Roles',
          to: '/admin/job-roles',
          iconKey: 'job-roles',
          activePaths: ['/admin/job-roles'],
        },
      ],
    },
    {
      title: 'Learning',
      items: [
        {
          id: 'training-catalog',
          label: 'Training Catalog',
          to: '/admin/courses',
          iconKey: 'training-catalog',
          activePaths: ['/admin/courses'],
        },
        {
          id: 'training-assignments',
          label: 'Training Assignments',
          to: '/admin/training-assignments',
          iconKey: 'training-assignments',
          activePaths: ['/admin/training-assignments', '/admin/enrollments'],
        },
        {
          id: 'assessments',
          label: 'Assessments',
          to: '/admin/quizzes-exams',
          iconKey: 'assessments',
          activePaths: ['/admin/quizzes-exams', '/admin/question-bank'],
        },
        {
          id: 'live-training',
          label: 'Live Training',
          to: '/admin/live-classes',
          iconKey: 'live-training',
          activePaths: ['/admin/live-classes'],
        },
      ],
    },
    {
      title: 'Skills & Compliance',
      items: [
        {
          id: 'skills',
          label: 'Skills',
          to: '/admin/skills',
          iconKey: 'skills',
          activePaths: ['/admin/skills'],
        },
        {
          id: 'certificates',
          label: 'Certifications',
          to: '/admin/certificates',
          iconKey: 'certificates',
          activePaths: ['/admin/certificates'],
        },
        {
          id: 'compliance',
          label: 'Compliance',
          to: '/admin/compliance',
          iconKey: 'compliance',
          activePaths: ['/admin/compliance'],
        },
      ],
    },
    {
      title: 'Engagement',
      items: [
        {
          id: 'announcements',
          label: 'Announcements',
          to: '/admin/announcements',
          iconKey: 'announcements',
          activePaths: ['/admin/announcements'],
        },
        {
          id: 'forum',
          label: 'Discussions',
          to: '/admin/discussion-forum',
          iconKey: 'forum',
          activePaths: ['/admin/discussion-forum'],
        },
      ],
    },
    {
      title: 'Administration',
      items: [
        {
          id: 'reports',
          label: 'Reports',
          to: '/admin/reports',
          iconKey: 'reports',
          activePaths: ['/admin/reports'],
        },
        {
          id: 'help-desk',
          label: 'Help Desk',
          to: '/admin/help-desk',
          iconKey: 'help-desk',
          activePaths: ['/admin/help-desk'],
        },
        {
          id: 'settings',
          label: 'Settings',
          to: '/admin/settings',
          iconKey: 'settings',
          activePaths: ['/admin/settings'],
        },
      ],
    },
  ],
  breadcrumbLabels: {
    '/admin': 'Dashboard',
    '/admin/organization': 'Organization Structure',
    '/admin/employees': 'Employees',
    '/admin/departments': 'Departments',
    '/admin/teams': 'Teams',
    '/admin/job-roles': 'Job Roles',
    '/admin/courses': 'Training Catalog',
    '/admin/training-assignments': 'Training Assignments',
    '/admin/enrollments': 'Training Assignments',
    '/admin/assignments': 'Training Tasks',
    '/admin/quizzes-exams': 'Assessments',
    '/admin/question-bank': 'Question Bank',
    '/admin/live-classes': 'Live Training',
    '/admin/skills': 'Skills',
    '/admin/certificates': 'Certifications',
    '/admin/compliance': 'Compliance',
    '/admin/announcements': 'Announcements',
    '/admin/discussion-forum': 'Discussions',
    '/admin/reports': 'Reports',
    '/admin/help-desk': 'Help Desk',
    '/admin/settings': 'Organization Settings',
    '/admin/instructors': 'Trainers',
    '/admin/admins': 'Administrators',
  },
}
