import type { EditionConfig, TerminologyMap } from './types'

const terminology: TerminologyMap = {
  organization: 'Organization',
  location: 'Branch / Office',
  department: 'Department',
  departments: 'Departments',
  team: 'Team',
  teams: 'Teams',
  employee: 'Employee',
  employees: 'Employees',
  trainer: 'Trainer',
  training: 'Training',
  trainingCatalog: 'Training Catalog',
  trainingAssignment: 'Training Assignments',
  course: 'Training Module',
  courses: 'Training Modules',
  enrollment: 'Assignment',
  enrollments: 'Training Assignments',
  certificate: 'Certification',
  certificates: 'Certifications',
  compliance: 'Compliance',
  adminRole: 'Learning Admin',
  learnerPortal: 'Employee Portal',
  cohort: 'Cohort',
  cohorts: 'Cohorts',
  trainingProgram: 'Training Program',
  trainingPrograms: 'Training Programs',
  trainingDivision: 'Division',
  trainingDivisions: 'Divisions',
  learner: 'Employee',
  learners: 'Employees',
  instructorPortal: 'Trainer Portal',
}

export const corporateEditionConfig: EditionConfig = {
  edition: 'corporate',
  defaultOrganizationName: 'Horizon Bank',
  terminology,
  modules: {
    campuses: false,
    colleges: false,
    programs: false,
    students: true,
    instructors: true,
    guardians: false,
    staff: false,
    enrollments: true,
    teams: true,
    employees: true,
    compliance: true,
    payments: false,
  },
  breadcrumbLabels: {
    '/admin/students': 'Employees',
    '/admin/instructors': 'Trainers',
    '/admin/courses': 'Training Catalog',
    '/admin/enrollments': 'Training Assignments',
    '/admin/institution/departments': 'Departments',
    '/admin/institution/structure': 'Organization Structure',
    '/admin/quizzes-exams': 'Assessments',
    '/admin/live-classes': 'Live Training',
    '/admin/certificates': 'Certifications',
    '/admin/discussion-forum': 'Discussions',
    '/admin/settings': 'Organization Settings',
  },
}
