import type { EditionConfig } from './types'

const trainingTerminology = {
  organization: 'Training Organization',
  location: 'Training Center',
  department: 'Training Division',
  team: 'Cohort',
  employee: 'Learner',
  employees: 'Learners',
  trainer: 'Trainer',
  training: 'Training Program',
  trainingCatalog: 'Course Catalog',
  trainingAssignment: 'Cohort Enrollments',
  course: 'Course',
  enrollment: 'Enrollment',
  certificate: 'Certificate of Completion',
  compliance: 'Accreditation & Compliance',
  adminRole: 'Training Administrator',
  learnerPortal: 'Learner Portal',
  cohort: 'Cohort',
  cohorts: 'Cohorts',
  trainingProgram: 'Training Program',
  trainingPrograms: 'Training Programs',
  trainingDivision: 'Training Division',
  trainingDivisions: 'Training Divisions',
  learner: 'Learner',
  learners: 'Learners',
} as const

export const trainingEditionConfig: EditionConfig = {
  edition: 'training_organization',
  tenantType: 'training_provider',
  defaultOrganizationName: 'Apex Training Institute',
  terminology: trainingTerminology,
  modules: {
    campuses: false,
    colleges: false,
    programs: true,
    students: true,
    instructors: true,
    guardians: false,
    enrollments: true,
    teams: false,
    employees: false,
    compliance: true,
    trainingDivisions: true,
    trainingPrograms: true,
    cohorts: true,
    learners: true,
    trainers: true,
  },
  navSections: [
    {
      title: 'Main',
      items: [
        {
          id: 'dashboard',
          label: 'Dashboard',
          to: '/admin',
          iconKey: 'dashboard',
          activePaths: ['/admin'],
        },
        {
          id: 'organization',
          label: 'Organization Structure',
          to: '/admin/organization',
          iconKey: 'organization',
          activePaths: ['/admin/organization', '/admin/training-organization'],
        },
      ],
    },
    {
      title: 'Training & Cohorts',
      items: [
        {
          id: 'training-programs',
          label: 'Training Programs',
          to: '/admin/training-programs',
          iconKey: 'training-programs',
          activePaths: ['/admin/training-programs'],
        },
        {
          id: 'cohorts',
          label: 'Cohorts',
          to: '/admin/cohorts',
          iconKey: 'cohorts',
          activePaths: ['/admin/cohorts'],
        },
        {
          id: 'training-catalog',
          label: 'Course Catalog',
          to: '/admin/courses',
          iconKey: 'training-catalog',
          activePaths: ['/admin/courses'],
        },
        {
          id: 'training-assignments',
          label: 'Cohort Enrollments',
          to: '/admin/enrollments',
          iconKey: 'training-assignments',
          activePaths: ['/admin/enrollments', '/admin/training-assignments'],
        },
      ],
    },
    {
      title: 'People',
      items: [
        {
          id: 'learners',
          label: 'Learners',
          to: '/admin/learners',
          iconKey: 'learners',
          activePaths: ['/admin/learners', '/admin/students'],
        },
        {
          id: 'trainers',
          label: 'Trainers',
          to: '/admin/trainers',
          iconKey: 'trainers',
          activePaths: ['/admin/trainers', '/admin/instructors'],
        },
      ],
    },
    {
      title: 'Delivery & Assessments',
      items: [
        {
          id: 'live-training',
          label: 'Live Training Sessions',
          to: '/admin/live-classes',
          iconKey: 'live-training',
          activePaths: ['/admin/live-classes'],
        },
        {
          id: 'assessments',
          label: 'Assessments & Quizzes',
          to: '/admin/quizzes-exams',
          iconKey: 'assessments',
          activePaths: ['/admin/quizzes-exams', '/admin/question-bank'],
        },
        {
          id: 'certificates',
          label: 'Certifications',
          to: '/admin/certificates',
          iconKey: 'certificates',
          activePaths: ['/admin/certificates'],
        },
      ],
    },
    {
      title: 'Engagement',
      items: [
        {
          id: 'announcements',
          label: 'Announcements',
          to: '/admin/announcements',
          iconKey: 'announcements',
          activePaths: ['/admin/announcements'],
        },
        {
          id: 'forum',
          label: 'Discussions',
          to: '/admin/discussion-forum',
          iconKey: 'forum',
          activePaths: ['/admin/discussion-forum'],
        },
      ],
    },
    {
      title: 'Administration',
      items: [
        {
          id: 'reports',
          label: 'Reports & Analytics',
          to: '/admin/reports',
          iconKey: 'reports',
          activePaths: ['/admin/reports'],
        },
        {
          id: 'help-desk',
          label: 'Help Desk',
          to: '/admin/help-desk',
          iconKey: 'help-desk',
          activePaths: ['/admin/help-desk'],
        },
        {
          id: 'settings',
          label: 'Settings',
          to: '/admin/settings',
          iconKey: 'settings',
          activePaths: ['/admin/settings'],
        },
      ],
    },
  ],
  breadcrumbLabels: {
    '/admin': 'Dashboard',
    '/admin/organization': 'Organization Structure',
    '/admin/training-organization': 'Organization Structure',
    '/admin/training-programs': 'Training Programs',
    '/admin/cohorts': 'Cohorts',
    '/admin/courses': 'Course Catalog',
    '/admin/enrollments': 'Cohort Enrollments',
    '/admin/training-assignments': 'Cohort Enrollments',
    '/admin/learners': 'Learners',
    '/admin/students': 'Learners',
    '/admin/trainers': 'Trainers',
    '/admin/instructors': 'Trainers',
    '/admin/live-classes': 'Live Training Sessions',
    '/admin/assignments': 'Tasks & Projects',
    '/admin/quizzes-exams': 'Assessments & Quizzes',
    '/admin/question-bank': 'Question Bank',
    '/admin/certificates': 'Certifications',
    '/admin/announcements': 'Announcements',
    '/admin/discussion-forum': 'Discussions',
    '/admin/reports': 'Reports & Analytics',
    '/admin/help-desk': 'Help Desk',
    '/admin/settings': 'Organization Settings',
    '/admin/admins': 'Administrators',
  },
}
