import type { EditionConfig, TerminologyMap } from './types'

const terminology: TerminologyMap = {
  organization: 'Training Organization',
  location: 'Training Center',
  department: 'Training Division',
  departments: 'Training Divisions',
  team: 'Cohort',
  teams: 'Cohorts',
  employee: 'Learner',
  employees: 'Learners',
  trainer: 'Trainer',
  training: 'Training Program',
  trainingCatalog: 'Course Catalog',
  trainingAssignment: 'Cohort Enrollments',
  course: 'Course',
  courses: 'Courses',
  enrollment: 'Enrollment',
  enrollments: 'Cohort Enrollments',
  certificate: 'Certificate of Completion',
  certificates: 'Certificates',
  compliance: 'Accreditation & Compliance',
  adminRole: 'Training Administrator',
  learnerPortal: 'Learner Portal',
  cohort: 'Cohort',
  cohorts: 'Cohorts',
  trainingProgram: 'Training Program',
  trainingPrograms: 'Training Programs',
  trainingDivision: 'Training Division',
  trainingDivisions: 'Training Divisions',
  learner: 'Learner',
  learners: 'Learners',
  instructorPortal: 'Trainer Portal',
}

export const trainingEditionConfig: EditionConfig = {
  edition: 'training_organization',
  defaultOrganizationName: 'Apex Training Institute',
  terminology,
  modules: {
    campuses: false,
    colleges: false,
    programs: true,
    students: true,
    instructors: true,
    guardians: false,
    staff: false,
    enrollments: true,
    teams: true,
    employees: false,
    compliance: true,
    payments: true,
  },
  breadcrumbLabels: {
    '/admin/students': 'Learners',
    '/admin/instructors': 'Trainers',
    '/admin/courses': 'Course Catalog',
    '/admin/enrollments': 'Cohort Enrollments',
    '/admin/institution/departments': 'Training Divisions',
    '/admin/institution/structure': 'Organization Structure',
    '/admin/institution/programs': 'Training Programs',
    '/admin/quizzes-exams': 'Assessments & Quizzes',
    '/admin/live-classes': 'Live Training Sessions',
    '/admin/certificates': 'Certifications',
    '/admin/discussion-forum': 'Discussions',
    '/admin/settings': 'Organization Settings',
  },
}
