import type { EditionConfig, TerminologyMap } from './types'

const terminology: TerminologyMap = {
  organization: 'Institution',
  location: 'Campus',
  department: 'Department',
  departments: 'Departments',
  team: 'Section',
  teams: 'Sections',
  employee: 'Staff Member',
  employees: 'Staff',
  trainer: 'Instructor',
  training: 'Learning',
  trainingCatalog: 'Courses',
  trainingAssignment: 'Enrollments',
  course: 'Course',
  courses: 'Courses',
  enrollment: 'Enrollment',
  enrollments: 'Enrollments',
  certificate: 'Certificate',
  certificates: 'Certificates',
  compliance: 'Compliance',
  adminRole: 'Institution Admin',
  learnerPortal: 'Student Portal',
  cohort: 'Class Section',
  cohorts: 'Class Sections',
  trainingProgram: 'Academic Program',
  trainingPrograms: 'Academic Programs',
  trainingDivision: 'College / School',
  trainingDivisions: 'Colleges / Schools',
  learner: 'Student',
  learners: 'Students',
  instructorPortal: 'Instructor Portal',
}

export const universityEditionConfig: EditionConfig = {
  edition: 'university',
  defaultOrganizationName: 'Berana University',
  terminology,
  modules: {
    campuses: true,
    colleges: true,
    programs: true,
    students: true,
    instructors: true,
    guardians: true,
    staff: true,
    enrollments: true,
    teams: false,
    employees: false,
    compliance: false,
    payments: true,
  },
  breadcrumbLabels: {},
}
