/** Collection keys used by useApiCollection (berana: prefix is legacy naming). */
export const STORAGE_KEYS = {
  session: 'berana:session',
  people: 'berana:people',
  campuses: 'berana:campuses',
  colleges: 'berana:colleges',
  departments: 'berana:departments',
  programs: 'berana:programs',
  academicYears: 'berana:academic-years',
  academicTerms: 'berana:academic-terms',
  courseOfferings: 'berana:course-offerings',
  courses: 'berana:courses',
  enrollments: 'berana:enrollments',
  certificates: 'berana:certificates',
  attendances: 'berana:attendances',
  lessonProgress: 'berana:lesson-progress',
  lessonResponses: 'berana:lesson-responses',
  settings: 'berana:settings',
  selectedCampus: 'berana:selectedCampus',
  reports: 'berana:reports',
  lmsActivity: 'berana:lms-activity',
  studentSettings: 'berana:student-settings',
  instructorSettings: 'berana:instructor-settings',
  staffSettings: 'berana:staff-settings',
  guardianSettings: 'berana:guardian-settings',
  helpDeskSettings: 'berana:help-desk-settings',
  announcements: 'berana:announcements',
  forumChats: 'berana:forum-chats',
  forumMessages: 'berana:forum-messages',
  forumReadState: 'berana:forum-read-state',
  liveSessions: 'berana:live-sessions',
  assignments: 'berana:assignments',
  quizzes: 'berana:quizzes',
  questionBank: 'berana:question-bank',
  studentSubmissions: 'berana:student-submissions',
  payments: 'berana:payments',
  helpDeskTickets: 'berana:help-desk-tickets',
  integrations: 'berana:integrations',
  // Corporate edition
  teams: 'berana:teams',
  jobRoles: 'berana:job-roles',
  skills: 'berana:skills',
} as const

export const STORAGE_EVENTS = {
  peopleUpdated: 'berana:people-updated',
  coursesUpdated: 'berana:courses-updated',
  enrollmentsUpdated: 'berana:enrollments-updated',
  certificatesUpdated: 'berana:certificates-updated',
  attendancesUpdated: 'berana:attendances-updated',
  lessonProgressUpdated: 'berana:lesson-progress-updated',
  lessonResponsesUpdated: 'berana:lesson-responses-updated',
  orgUpdated: 'berana:org-updated',
  academicUpdated: 'berana:academic-updated',
  announcementsUpdated: 'berana:announcements-updated',
  forumUpdated: 'berana:forum-updated',
  assessmentsUpdated: 'berana:assessments-updated',
  platformUpdated: 'berana:platform-updated',
} as const
