import type { StudentDashboardData } from '../types'

const studentDashboardData: StudentDashboardData = {
	studentName: 'Amina Lemma',
	program: 'BSc Computer Science',
	term: 'Fall 2026',
	standing: 'On track for distinction',
	stats: [
		{ label: 'Active Courses', value: '6', detail: '2 lab courses, 4 theory modules' },
		{ label: 'Due This Week', value: '4', detail: '1 quiz, 2 assignments, 1 reflection' },
		{ label: 'Avg. Quiz Score', value: '88%', detail: 'Across the last 3 assessments' },
		{ label: 'Current GPA', value: '3.84', detail: 'Based on 48 graded credits' },
		{ label: 'Upcoming Meetings', value: '3', detail: '1 lecture, 1 office hour, 1 project sync' },
	],
	resources: [
		{
			id: 'res-1',
			title: 'Software Engineering Syllabus',
			course: 'CSE 402',
			kind: 'Syllabus',
			size: '1.2 MB',
			updatedAt: 'Updated today',
			href: '#resource-syllabus',
		},
		{
			id: 'res-2',
			title: 'Lecture 08: API Design Notes',
			course: 'CSE 402',
			kind: 'Lecture Notes',
			size: '8.4 MB',
			updatedAt: 'Updated yesterday',
			href: '#resource-notes',
		},
		{
			id: 'res-3',
			title: 'Research Reading Pack',
			course: 'CSE 410',
			kind: 'Reading',
			size: '24 MB',
			updatedAt: 'Updated 2 days ago',
			href: '#resource-reading',
		},
		{
			id: 'res-4',
			title: 'Recursion Demo Video',
			course: 'CSE 301',
			kind: 'Video',
			size: '310 MB',
			updatedAt: 'Updated this week',
			href: '#resource-video',
		},
	],
	quizzes: [
		{
			id: 'quiz-1',
			title: 'Database Normalization Checkpoint',
			course: 'CSE 311',
			dueAt: 'Due Wed, 8:00 PM',
			questions: 18,
			duration: '20 min',
			status: 'Open',
		},
		{
			id: 'quiz-2',
			title: 'Data Structures Weekly Assessment',
			course: 'CSE 301',
			dueAt: 'Due Fri, 6:00 PM',
			questions: 22,
			duration: '25 min',
			status: 'Completed',
			score: '92%',
		},
		{
			id: 'quiz-3',
			title: 'User Experience Fundamentals',
			course: 'DES 210',
			dueAt: 'Unlocks Sat, 9:00 AM',
			questions: 12,
			duration: '15 min',
			status: 'Locked',
		},
	],
	assignments: [
		{
			id: 'ass-1',
			title: 'Frontend Project Critique',
			course: 'CSE 402',
			dueAt: 'Due Thu, 11:59 PM',
			brief: 'Upload a 2-page analysis with annotated screenshots and a reference list.',
			acceptedFormats: ['PDF', 'DOCX'],
			status: 'Ready to submit',
		},
		{
			id: 'ass-2',
			title: 'Algorithm Trace Report',
			course: 'CSE 301',
			dueAt: 'Due Fri, 5:00 PM',
			brief: 'Submit your solution trace and complexity notes in the dropbox.',
			acceptedFormats: ['PDF'],
			status: 'Submitted',
			feedback: 'Instructor comment ready after grading.',
		},
		{
			id: 'ass-3',
			title: 'Research Reflection Journal',
			course: 'CSE 410',
			dueAt: 'Due Sun, 9:00 PM',
			brief: 'Attach your weekly journal and cite at least two journal papers.',
			acceptedFormats: ['PDF', 'DOCX', 'TXT'],
			status: 'Awaiting review',
		},
	],
	schedule: [
		{
			id: 'evt-1',
			title: 'Advanced Programming Lecture',
			course: 'CSE 402',
			startAt: 'Mon 9:00 AM',
			type: 'Live class',
			location: 'Zoom room 4',
			accent: 'bg-lemon-500',
		},
		{
			id: 'evt-2',
			title: 'Database Lab Review',
			course: 'CSE 311',
			startAt: 'Tue 2:00 PM',
			type: 'Office hour',
			location: 'Faculty hub',
			accent: 'bg-navy-500',
		},
		{
			id: 'evt-3',
			title: 'Algorithms Midterm',
			course: 'CSE 301',
			startAt: 'Thu 10:30 AM',
			type: 'Exam',
			location: 'Main exam hall',
			accent: 'bg-danger',
		},
		{
			id: 'evt-4',
			title: 'Reflection journal upload closes',
			course: 'CSE 410',
			startAt: 'Sun 9:00 PM',
			type: 'Deadline',
			location: 'Assignment dropbox',
			accent: 'bg-info',
		},
	],
	grades: [
		{
			id: 'grade-1',
			course: 'CSE 402 Software Engineering',
			grade: 'A-',
			percent: 91,
			progress: 91,
			feedback: 'Excellent implementation discipline and clear documentation.',
			instructor: 'Dr. Mensah',
			updatedAt: 'Updated 2 hours ago',
		},
		{
			id: 'grade-2',
			course: 'CSE 311 Database Systems',
			grade: 'A',
			percent: 95,
			progress: 95,
			feedback: 'Your normalization answers were precise and well argued.',
			instructor: 'Prof. Adeyemi',
			updatedAt: 'Updated yesterday',
		},
		{
			id: 'grade-3',
			course: 'CSE 301 Algorithms',
			grade: 'B+',
			percent: 86,
			progress: 86,
			feedback: 'Strong grasp of recursion. Improve proof clarity on edge cases.',
			instructor: 'Dr. Chen',
			updatedAt: 'Updated this week',
		},
		{
			id: 'grade-4',
			course: 'DES 210 UX Fundamentals',
			grade: 'A',
			percent: 93,
			progress: 93,
			feedback: 'Beautiful wireframes and a thoughtful user journey summary.',
			instructor: 'Ms. Diallo',
			updatedAt: 'Updated this week',
		},
	],
}

export async function fetchStudentDashboardData() {
	return Promise.resolve(studentDashboardData)
}
